theme: jekyll-theme-minimal
logo: https://labs.utsouthwestern.edu/sites/default/files/styles/coh_small_landscape/public/2023-01/output-onlinepngtools%20%281%29_0.png?h=d18e10ad&itok=jgyUVhxw
title: Lilith's Bioinformatics Class (BIMM143, Spring 2024)
