---
title: "class 17"
format: html
---

Class 17$ls
Class 17.Rproj
Class 17$
Class 17$
Class 17$
Class 17$ssh -i "~/Downloads/bimm143_lilith.pem" ubuntu@ec2-18-237-17-121.us-west-2.compute.amazonaws.com
Welcome to Ubuntu 24.04 LTS (GNU/Linux 6.8.0-1008-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

 System information as of Tue May 28 17:54:42 UTC 2024

  System load:  0.0               Temperature:           -273.1 C
  Usage of /:   8.4% of 95.82GB   Processes:             159
  Memory usage: 1%                Users logged in:       1
  Swap usage:   0%                IPv4 address for ens5: 172.31.3.125


Expanded Security Maintenance for Applications is not enabled.

6 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


*** System restart required ***
Last login: Tue May 28 16:53:32 2024 from 69.196.45.168
ubuntu@ip-172-31-3-125:~$ ls
class17  sratoolkit.current-ubuntu64.tar  work
ubuntu@ip-172-31-3-125:~$ cd class17
ubuntu@ip-172-31-3-125:~/class17$ ls
SRR600956  SRR600956.fastq  sratoolkit.3.1.1-ubuntu64  sratoolkit.current-ubuntu64.tar.gz
ubuntu@ip-172-31-3-125:~/class17$ grep -c "@SRR600956" SRR600956.fastq
25849655
ubuntu@ip-172-31-3-125:~/class17$ 
ubuntu@ip-172-31-3-125:~/class17$ prefetch SRR2156848
Command 'prefetch' not found, but can be installed with:
sudo apt install sra-toolkit
ubuntu@ip-172-31-3-125:~/class17$ pwd
/home/ubuntu/class17
ubuntu@ip-172-31-3-125:~/class17$ cd
ubuntu@ip-172-31-3-125:~$ prefetch SRR2156848
Command 'prefetch' not found, but can be installed with:
sudo apt install sra-toolkit
ubuntu@ip-172-31-3-125:~$  ~/class17/sratoolkit.3.1.1-ubuntu64/bin/prefetch --version

/home/ubuntu/class17/sratoolkit.3.1.1-ubuntu64/bin/prefetch : 3.1.1

ubuntu@ip-172-31-3-125:~$ export PATH=$PATH:/home/ubuntu/class17/sratoolkit.3.1.1-ubuntu64/bin
ubuntu@ip-172-31-3-125:~$ prefetch
Usage:
  prefetch [options] <SRA accession> [...]
  Download SRA files and their dependencies

  prefetch [options] --perm <JWT cart file> <SRA accession> [...]
  Download SRA files and their dependencies from JWT cart

  prefetch [options] --cart <kart file>
  Download cart file

  prefetch [options] <URL> --output-file <FILE>
  Download URL to FILE

  prefetch [options] <URL> [...] --output-directory <DIRECTORY>
  Download URL or URL-s to DIRECTORY

  prefetch [options] <SRA file> [...]
  Check SRA file for missed dependencies and download them

ubuntu@ip-172-31-3-125:~$ prefetch SRR2156848
2024-05-28T17:56:39 prefetch.3.1.1: 1) Resolving 'SRR2156848'...
2024-05-28T17:56:39 prefetch.3.1.1: Current preference is set to retrieve SRA Normalized Format files with full base quality scores
2024-05-28T17:56:40 prefetch.3.1.1: 1) Downloading 'SRR2156848'...
2024-05-28T17:56:40 prefetch.3.1.1:  SRA Normalized Format file is being retrieved
2024-05-28T17:56:40 prefetch.3.1.1:  Downloading via HTTPS...
2024-05-28T17:56:48 prefetch.3.1.1:  HTTPS download succeed
2024-05-28T17:56:49 prefetch.3.1.1:  'SRR2156848' is valid: 227793481 bytes were streamed from 227787045
2024-05-28T17:56:49 prefetch.3.1.1: 1) 'SRR2156848' was downloaded successfully
2024-05-28T17:56:49 prefetch.3.1.1: 'SRR2156848' has 0 unresolved dependencies
ubuntu@ip-172-31-3-125:~$ prefetch SRR600956
2024-05-28T17:57:29 prefetch.3.1.1: 1) Resolving 'SRR600956'...
2024-05-28T17:57:29 prefetch.3.1.1: Current preference is set to retrieve SRA Normalized Format files with full base quality scores
2024-05-28T17:57:30 prefetch.3.1.1: 1) Downloading 'SRR600956'...
2024-05-28T17:57:30 prefetch.3.1.1:  SRA Normalized Format file is being retrieved
2024-05-28T17:57:30 prefetch.3.1.1:  Downloading via HTTPS...
2024-05-28T17:57:42 prefetch.3.1.1:  HTTPS download succeed
2024-05-28T17:57:43 prefetch.3.1.1:  'SRR600956' is valid: 604278382 bytes were streamed from 604269474
2024-05-28T17:57:43 prefetch.3.1.1: 1) 'SRR600956' was downloaded successfully
ubuntu@ip-172-31-3-125:~$ fastq-dump SRR600956
Read 25849655 spots for SRR600956
Written 25849655 spots for SRR600956
ubuntu@ip-172-31-3-125:~$ fastq-dump --split-3 SRR2156848
Read 2959900 spots for SRR2156848
Written 2959900 spots for SRR2156848
ubuntu@ip-172-31-3-125:~$ pwd
/home/ubuntu
ubuntu@ip-172-31-3-125:~$ ls
SRR2156848          SRR2156848_2.fastq  SRR600956.fastq  sratoolkit.current-ubuntu64.tar
SRR2156848_1.fastq  SRR600956           class17          work
ubuntu@ip-172-31-3-125:~$ grep -c "@SRR2156848" *fastq
SRR2156848_1.fastq:2959900
SRR2156848_2.fastq:2959900
SRR600956.fastq:0
ubuntu@ip-172-31-3-125:~$ prefetch SRR2156849 SRR2156850 SRR2156851
2024-05-28T18:02:54 prefetch.3.1.1: 1) Resolving 'SRR2156849'...
2024-05-28T18:02:55 prefetch.3.1.1: Current preference is set to retrieve SRA Normalized Format files with full base quality scores
2024-05-28T18:02:55 prefetch.3.1.1: 1) Downloading 'SRR2156849'...
2024-05-28T18:02:55 prefetch.3.1.1:  SRA Normalized Format file is being retrieved
2024-05-28T18:02:55 prefetch.3.1.1:  Downloading via HTTPS...
2024-05-28T18:03:00 prefetch.3.1.1:  HTTPS download succeed
2024-05-28T18:03:00 prefetch.3.1.1:  'SRR2156849' is valid: 226003506 bytes were streamed from 225988042
2024-05-28T18:03:00 prefetch.3.1.1: 1) 'SRR2156849' was downloaded successfully
2024-05-28T18:03:00 prefetch.3.1.1: 'SRR2156849' has 0 unresolved dependencies
2024-05-28T18:03:00 prefetch.3.1.1: 2) Resolving 'SRR2156850'...
2024-05-28T18:03:01 prefetch.3.1.1: 2) Downloading 'SRR2156850'...
2024-05-28T18:03:01 prefetch.3.1.1:  SRA Normalized Format file is being retrieved
2024-05-28T18:03:01 prefetch.3.1.1:  Downloading via HTTPS...
2024-05-28T18:03:05 prefetch.3.1.1:  HTTPS download succeed
2024-05-28T18:03:06 prefetch.3.1.1:  'SRR2156850' is valid: 201306539 bytes were streamed from 201293369
2024-05-28T18:03:06 prefetch.3.1.1: 2) 'SRR2156850' was downloaded successfully
2024-05-28T18:03:06 prefetch.3.1.1: 'SRR2156850' has 0 unresolved dependencies
2024-05-28T18:03:06 prefetch.3.1.1: 3) Resolving 'SRR2156851'...
2024-05-28T18:03:07 prefetch.3.1.1: 3) Downloading 'SRR2156851'...
2024-05-28T18:03:07 prefetch.3.1.1:  SRA Normalized Format file is being retrieved
2024-05-28T18:03:07 prefetch.3.1.1:  Downloading via HTTPS...
2024-05-28T18:03:10 prefetch.3.1.1:  HTTPS download succeed
2024-05-28T18:03:11 prefetch.3.1.1:  'SRR2156851' is valid: 179358367 bytes were streamed from 179344843
2024-05-28T18:03:11 prefetch.3.1.1: 3) 'SRR2156851' was downloaded successfully
2024-05-28T18:03:11 prefetch.3.1.1: 'SRR2156851' has 0 unresolved dependencies
ubuntu@ip-172-31-3-125:~$ fastq-dump --split-3 SRR2156849 SRR2156850 SRR2156851
Read 2985576 spots for SRR2156849
Written 2985576 spots for SRR2156849
Read 2669778 spots for SRR2156850
Written 2669778 spots for SRR2156850
Read 2369745 spots for SRR2156851
Written 2369745 spots for SRR2156851
ubuntu@ip-172-31-3-125:~$ grep -c "@SRR21568" *fastq
SRR2156848_1.fastq:2959900
SRR2156848_2.fastq:2959900
SRR2156849_1.fastq:2985576
SRR2156849_2.fastq:2985576
SRR2156850_1.fastq:2669778
SRR2156850_2.fastq:2669778
SRR2156851_1.fastq:2369745
SRR2156851_2.fastq:2369745
SRR600956.fastq:0
ubuntu@ip-172-31-3-125:~$ du -h *.fastq
640M    SRR2156848_1.fastq
640M    SRR2156848_2.fastq
645M    SRR2156849_1.fastq
645M    SRR2156849_2.fastq
577M    SRR2156850_1.fastq
577M    SRR2156850_2.fastq
512M    SRR2156851_1.fastq
512M    SRR2156851_2.fastq
4.9G    SRR600956.fastq
ubuntu@ip-172-31-3-125:~$ pwd/home/ubuntu
ubuntu@ip-172-31-3-125:~$ cd class17
ubuntu@ip-172-31-3-125:~/class17$ wget https://github.com/pachterlab/kallisto/releases/download/v0.44.0/kallisto_linux-v0.44.0.tar.gz
--2024-05-28 18:16:19--  https://github.com/pachterlab/kallisto/releases/download/v0.44.0/kallisto_linux-v0.44.0.tar.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/26562905/b78619ae-0542-11e8-908e-6777f5455785?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240528%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240528T181559Z&X-Amz-Expires=300&X-Amz-Signature=91ff28236f5d3a95b450943df26e4081be229361f1f45967162bc1ee8bc6ae5e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=26562905&response-content-disposition=attachment%3B%20filename%3Dkallisto_linux-v0.44.0.tar.gz&response-content-type=application%2Foctet-stream [following]
--2024-05-28 18:16:19--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/26562905/b78619ae-0542-11e8-908e-6777f5455785?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240528%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240528T181559Z&X-Amz-Expires=300&X-Amz-Signature=91ff28236f5d3a95b450943df26e4081be229361f1f45967162bc1ee8bc6ae5e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=26562905&response-content-disposition=attachment%3B%20filename%3Dkallisto_linux-v0.44.0.tar.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6668961 (6.4M) [application/octet-stream]
Saving to: ‘kallisto_linux-v0.44.0.tar.gz’

kallisto_linux-v0.44.0 100%[============================>]   6.36M  --.-KB/s    in 0.06s   

2024-05-28 18:16:20 (99.0 MB/s) - ‘kallisto_linux-v0.44.0.tar.gz’ saved [6668961/6668961]

ubuntu@ip-172-31-3-125:~/class17$ gunzup kallisto_linux-v0.44.0.tar.gz 
Command 'gunzup' not found, did you mean:
  command 'gunzip' from deb gzip (1.12-1ubuntu1)
Try: sudo apt install <deb name>
ubuntu@ip-172-31-3-125:~/class17$ gunzip kallisto_linux-v0.44.0.tar.gz 
ubuntu@ip-172-31-3-125:~/class17$ tar -xvf kallisto_linux-v0.44.0.tar 
kallisto_linux-v0.44.0/
kallisto_linux-v0.44.0/license.txt
kallisto_linux-v0.44.0/kallisto
kallisto_linux-v0.44.0/test/
kallisto_linux-v0.44.0/test/chrom.txt
kallisto_linux-v0.44.0/test/transcripts.gtf.gz
kallisto_linux-v0.44.0/test/reads_2.fastq.gz
kallisto_linux-v0.44.0/test/transcripts.fasta.gz
kallisto_linux-v0.44.0/test/README.md
kallisto_linux-v0.44.0/test/Snakefile
kallisto_linux-v0.44.0/test/reads_1.fastq.gz
kallisto_linux-v0.44.0/README.md
ubuntu@ip-172-31-3-125:~/class17$ ls
SRR600956        kallisto_linux-v0.44.0      sratoolkit.3.1.1-ubuntu64
SRR600956.fastq  kallisto_linux-v0.44.0.tar  sratoolkit.current-ubuntu64.tar.gz
ubuntu@ip-172-31-3-125:~/class17$ ls kallisto_linux-v0.44.0
README.md  kallisto  license.txt  test
ubuntu@ip-172-31-3-125:~/class17$ ls kallisto_linux-v0.44.0/kallisto 
kallisto_linux-v0.44.0/kallisto
ubuntu@ip-172-31-3-125:~/class17$ cd kallisto_linux-v0.44.0/
ubuntu@ip-172-31-3-125:~/class17/kallisto_linux-v0.44.0$ pwd
/home/ubuntu/class17/kallisto_linux-v0.44.0
ubuntu@ip-172-31-3-125:~/class17/kallisto_linux-v0.44.0$ export PATH=$PATH:/home/ubuntu/class17/kallisto_linux-v0.44.0
ubuntu@ip-172-31-3-125:~/class17/kallisto_linux-v0.44.0$ kallisto --version
Error: invalid command --version
kallisto 0.44.0

Usage: kallisto <CMD> [arguments] ..

Where <CMD> can be one of:

    index         Builds a kallisto index 
    quant         Runs the quantification algorithm 
    pseudo        Runs the pseudoalignment step 
    h5dump        Converts HDF5-formatted results to plaintext
    inspect       Inspects and gives information about an index
    version       Prints version information
    cite          Prints citation information

Running kallisto <CMD> without arguments prints usage information for <CMD>

ubuntu@ip-172-31-3-125:~/class17/kallisto_linux-v0.44.0$ cd class17
-bash: cd: class17: No such file or directory
ubuntu@ip-172-31-3-125:~/class17/kallisto_linux-v0.44.0$ cd ..
ubuntu@ip-172-31-3-125:~/class17$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/class17/sratoolkit.3.1.1-ubuntu64/bin:/home/ubuntu/class17/kallisto_linux-v0.44.0
ubuntu@ip-172-31-3-125:~/class17$ 